<?php
/**
 * UserRequestQuery
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Dastra API
 *
 * Dastra's public REST API
 *
 * The version of the OpenAPI document: v1
 * Contact: antoine.bidault@dastra.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UserRequestQuery Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class UserRequestQuery implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UserRequestQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'overtaking' => 'bool',
        'archived' => 'bool',
        'q' => 'string',
        'widget_id' => 'int',
        'states' => '\OpenAPI\Client\Model\UserRequestState[]',
        'purposes' => '\OpenAPI\Client\Model\PurposeType[]',
        'area_id' => 'int',
        'users' => 'int[]',
        'ids' => 'int[]',
        'tags' => 'int[]',
        'page' => 'int',
        'size' => 'int',
        'skip' => 'int',
        'sort_by' => 'string',
        'asc' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'overtaking' => null,
        'archived' => null,
        'q' => null,
        'widget_id' => 'int32',
        'states' => null,
        'purposes' => null,
        'area_id' => 'int32',
        'users' => 'int32',
        'ids' => 'int32',
        'tags' => 'int32',
        'page' => 'int32',
        'size' => 'int32',
        'skip' => 'int32',
        'sort_by' => null,
        'asc' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'overtaking' => 'overtaking',
        'archived' => 'archived',
        'q' => 'q',
        'widget_id' => 'widgetId',
        'states' => 'states',
        'purposes' => 'purposes',
        'area_id' => 'areaId',
        'users' => 'users',
        'ids' => 'ids',
        'tags' => 'tags',
        'page' => 'page',
        'size' => 'size',
        'skip' => 'skip',
        'sort_by' => 'sortBy',
        'asc' => 'asc'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'overtaking' => 'setOvertaking',
        'archived' => 'setArchived',
        'q' => 'setQ',
        'widget_id' => 'setWidgetId',
        'states' => 'setStates',
        'purposes' => 'setPurposes',
        'area_id' => 'setAreaId',
        'users' => 'setUsers',
        'ids' => 'setIds',
        'tags' => 'setTags',
        'page' => 'setPage',
        'size' => 'setSize',
        'skip' => 'setSkip',
        'sort_by' => 'setSortBy',
        'asc' => 'setAsc'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'overtaking' => 'getOvertaking',
        'archived' => 'getArchived',
        'q' => 'getQ',
        'widget_id' => 'getWidgetId',
        'states' => 'getStates',
        'purposes' => 'getPurposes',
        'area_id' => 'getAreaId',
        'users' => 'getUsers',
        'ids' => 'getIds',
        'tags' => 'getTags',
        'page' => 'getPage',
        'size' => 'getSize',
        'skip' => 'getSkip',
        'sort_by' => 'getSortBy',
        'asc' => 'getAsc'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['overtaking'] = $data['overtaking'] ?? null;
        $this->container['archived'] = $data['archived'] ?? null;
        $this->container['q'] = $data['q'] ?? null;
        $this->container['widget_id'] = $data['widget_id'] ?? null;
        $this->container['states'] = $data['states'] ?? null;
        $this->container['purposes'] = $data['purposes'] ?? null;
        $this->container['area_id'] = $data['area_id'] ?? null;
        $this->container['users'] = $data['users'] ?? null;
        $this->container['ids'] = $data['ids'] ?? null;
        $this->container['tags'] = $data['tags'] ?? null;
        $this->container['page'] = $data['page'] ?? null;
        $this->container['size'] = $data['size'] ?? null;
        $this->container['skip'] = $data['skip'] ?? null;
        $this->container['sort_by'] = $data['sort_by'] ?? null;
        $this->container['asc'] = $data['asc'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets overtaking
     *
     * @return bool|null
     */
    public function getOvertaking()
    {
        return $this->container['overtaking'];
    }

    /**
     * Sets overtaking
     *
     * @param bool|null $overtaking overtaking
     *
     * @return self
     */
    public function setOvertaking($overtaking)
    {
        $this->container['overtaking'] = $overtaking;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool|null
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param bool|null $archived archived
     *
     * @return self
     */
    public function setArchived($archived)
    {
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets q
     *
     * @return string|null
     */
    public function getQ()
    {
        return $this->container['q'];
    }

    /**
     * Sets q
     *
     * @param string|null $q q
     *
     * @return self
     */
    public function setQ($q)
    {
        $this->container['q'] = $q;

        return $this;
    }

    /**
     * Gets widget_id
     *
     * @return int|null
     */
    public function getWidgetId()
    {
        return $this->container['widget_id'];
    }

    /**
     * Sets widget_id
     *
     * @param int|null $widget_id widget_id
     *
     * @return self
     */
    public function setWidgetId($widget_id)
    {
        $this->container['widget_id'] = $widget_id;

        return $this;
    }

    /**
     * Gets states
     *
     * @return \OpenAPI\Client\Model\UserRequestState[]|null
     */
    public function getStates()
    {
        return $this->container['states'];
    }

    /**
     * Sets states
     *
     * @param \OpenAPI\Client\Model\UserRequestState[]|null $states states
     *
     * @return self
     */
    public function setStates($states)
    {
        $this->container['states'] = $states;

        return $this;
    }

    /**
     * Gets purposes
     *
     * @return \OpenAPI\Client\Model\PurposeType[]|null
     */
    public function getPurposes()
    {
        return $this->container['purposes'];
    }

    /**
     * Sets purposes
     *
     * @param \OpenAPI\Client\Model\PurposeType[]|null $purposes purposes
     *
     * @return self
     */
    public function setPurposes($purposes)
    {
        $this->container['purposes'] = $purposes;

        return $this;
    }

    /**
     * Gets area_id
     *
     * @return int|null
     */
    public function getAreaId()
    {
        return $this->container['area_id'];
    }

    /**
     * Sets area_id
     *
     * @param int|null $area_id area_id
     *
     * @return self
     */
    public function setAreaId($area_id)
    {
        $this->container['area_id'] = $area_id;

        return $this;
    }

    /**
     * Gets users
     *
     * @return int[]|null
     */
    public function getUsers()
    {
        return $this->container['users'];
    }

    /**
     * Sets users
     *
     * @param int[]|null $users users
     *
     * @return self
     */
    public function setUsers($users)
    {
        $this->container['users'] = $users;

        return $this;
    }

    /**
     * Gets ids
     *
     * @return int[]|null
     */
    public function getIds()
    {
        return $this->container['ids'];
    }

    /**
     * Sets ids
     *
     * @param int[]|null $ids ids
     *
     * @return self
     */
    public function setIds($ids)
    {
        $this->container['ids'] = $ids;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return int[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param int[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets page
     *
     * @return int|null
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int|null $page page
     *
     * @return self
     */
    public function setPage($page)
    {
        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int|null $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets skip
     *
     * @return int|null
     */
    public function getSkip()
    {
        return $this->container['skip'];
    }

    /**
     * Sets skip
     *
     * @param int|null $skip skip
     *
     * @return self
     */
    public function setSkip($skip)
    {
        $this->container['skip'] = $skip;

        return $this;
    }

    /**
     * Gets sort_by
     *
     * @return string|null
     */
    public function getSortBy()
    {
        return $this->container['sort_by'];
    }

    /**
     * Sets sort_by
     *
     * @param string|null $sort_by sort_by
     *
     * @return self
     */
    public function setSortBy($sort_by)
    {
        $this->container['sort_by'] = $sort_by;

        return $this;
    }

    /**
     * Gets asc
     *
     * @return bool|null
     */
    public function getAsc()
    {
        return $this->container['asc'];
    }

    /**
     * Sets asc
     *
     * @param bool|null $asc asc
     *
     * @return self
     */
    public function setAsc($asc)
    {
        $this->container['asc'] = $asc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


