<?php
/**
 * UserRequestsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Dastra API
 *
 * Dastra's public REST API
 *
 * The version of the OpenAPI document: v1
 * Contact: antoine.bidault@dastra.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserRequestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserRequestsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for userRequestsArchive
     *
     * Archive an existing user request by id  It set the current state of the request to \"Archived\" state.
     *
     */
    public function testUserRequestsArchive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsColumns
     *
     * .
     *
     */
    public function testUserRequestsColumns()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsCreate
     *
     * .
     *
     */
    public function testUserRequestsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsDelete
     *
     * It remove definitly.
     *
     */
    public function testUserRequestsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsExport
     *
     * Export the records in any format.
     *
     */
    public function testUserRequestsExport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsFind
     *
     * Get an existing user request by id.
     *
     */
    public function testUserRequestsFind()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsList
     *
     * User request list.
     *
     */
    public function testUserRequestsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsPatch
     *
     * Patch an application.
     *
     */
    public function testUserRequestsPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsRestore
     *
     * .
     *
     */
    public function testUserRequestsRestore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsSetIdentityValidation
     *
     * Switching the identity validation state.
     *
     */
    public function testUserRequestsSetIdentityValidation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsStats
     *
     * .
     *
     */
    public function testUserRequestsStats()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsUpdate
     *
     * Edit a user request.
     *
     */
    public function testUserRequestsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userRequestsUpdateWorkflow
     *
     * Switching the current state.
     *
     */
    public function testUserRequestsUpdateWorkflow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
